services:
    luisa.admin.fotohome:
        class: Luisa\BackendBundle\Admin\FotoHomeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Home, label: "Foto",icon: "<i class=\"fa fa-picture-o\"></i>"  }
        arguments:
            - ~
            - Luisa\BackendBundle\Entity\FotoHome
            - 'SonataAdminBundle:CRUD'
    luisa.admin.videohome:
        class: Luisa\BackendBundle\Admin\VideoHomeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Home, label: "Video",icon: "<i class=\"fa fa-video-camera\"></i>"  }
        arguments:
            - ~
            - Luisa\BackendBundle\Entity\VideoHome
            - 'SonataAdminBundle:CRUD'
    luisa.admin.video:
        class: Luisa\BackendBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Video, label: "Video",icon: "<i class=\"fa fa-video-camera\"></i>"  }
        arguments:
            - ~
            - Luisa\BackendBundle\Entity\Video
            - 'SonataAdminBundle:CRUD'
    luisa.admin.fotocategoria:
        class: Luisa\BackendBundle\Admin\FotoCategoriaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foto, label: "Categoria",icon: "<i class=\"fa fa-camera-retro\"></i>" }
        arguments:
            - ~
            - Luisa\BackendBundle\Entity\FotoCategoria
            - 'SonataAdminBundle:CRUD'
    luisa.admin.foto:
        class: Luisa\BackendBundle\Admin\FotoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foto, label: "Foto",icon: "<i class=\"fa fa-camera-retro\"></i>" }
        arguments:
            - ~
            - Luisa\BackendBundle\Entity\Foto
            - 'SonataAdminBundle:CRUD'
    luisa.admin.image:
        class: Luisa\BackendBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Image, label: "Image",icon: "<i class=\"fa fa-picture-o\"></i>"  }
        arguments:
            - ~
            -  Application\Sonata\MediaBundle\Entity\Media
            - 'SonataAdminBundle:CRUD'
