<?php

namespace Luisa\BackendBundle\Repository;

/**
 * ArticoliRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticoliRepository extends \Doctrine\ORM\EntityRepository
{
}
