<?php

namespace Luisa\BackendBundle\Repository;

/**
 * FotoInternalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoInternalRepository extends \Doctrine\ORM\EntityRepository
{
}
