<?php

namespace Luisa\BackendBundle\Repository;

/**
 * FotoHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoHomeRepository extends \Doctrine\ORM\EntityRepository
{
}
