<?php

namespace Luisa\BackendBundle\Repository;

/**
 * VideoInternalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoInternalRepository extends \Doctrine\ORM\EntityRepository
{
}
