<?php

namespace Luisa\BackendBundle\Repository;

/**
 * VideoHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoHomeRepository extends \Doctrine\ORM\EntityRepository
{
}
