<?php

namespace Luisa\BackendBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLatestVideo($limit, $offsetvideo = null)
    {
        $qb = $this->createQueryBuilder('v');

        $qb
            ->where('v.active = 1')
            ->orderBy('v.id', 'DESC')
        ;

        if($offsetvideo) {
            $qb
                ->setFirstResult($offsetvideo)
            ;
        }

        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
